// GET /api/audit-pack/registry
//
// Returns the history of audit packs generated by the current session org.
// For cabinet users this includes packs generated for any portfolio client.

import { NextResponse } from "next/server"

import { listAuditPackRegistry } from "@/lib/server/audit-pack-builder"
import { getOrgContext } from "@/lib/server/org-context"

export async function GET() {
  try {
    const ctx = await getOrgContext()
    const packs = await listAuditPackRegistry(ctx.orgId)
    return NextResponse.json({ packs, total: packs.length })
  } catch (err) {
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Eroare la încărcarea registrului." },
      { status: 500 }
    )
  }
}
